import type { ScoredCandidate, RedFlag, EvidenceItem } from '@sourcerer/core';

export function renderReport(
  candidates: ScoredCandidate[],
  metadata?: Record<string, unknown>,
): string {
  const parts: string[] = [];
  parts.push(renderHeader(candidates, metadata));

  const tiers = [1, 2, 3] as const;
  for (const tier of tiers) {
    const tierCandidates = candidates
      .filter((c) => c.tier === tier)
      .sort((a, b) => b.score.total - a.score.total);
    if (tierCandidates.length > 0) {
      parts.push(renderTierSection(tier, tierCandidates));
    }
  }

  parts.push(renderFooter());
  return parts.join('\n');
}

function renderHeader(
  candidates: ScoredCandidate[],
  metadata?: Record<string, unknown>,
): string {
  const now = new Date().toISOString();
  const t1 = candidates.filter((c) => c.tier === 1).length;
  const t2 = candidates.filter((c) => c.tier === 2).length;
  const t3 = candidates.filter((c) => c.tier === 3).length;

  const tierBreakdown = [
    t1 > 0 ? `${t1} Tier 1` : null,
    t2 > 0 ? `${t2} Tier 2` : null,
    t3 > 0 ? `${t3} Tier 3` : null,
  ]
    .filter(Boolean)
    .join(', ');

  const lines = [`# Sourcerer Report`, ''];
  lines.push(
    `**Generated:** ${now}  `,
  );
  lines.push(
    `**Candidates:** ${candidates.length} total${tierBreakdown ? ` (${tierBreakdown})` : ''}`,
  );

  if (metadata && Object.keys(metadata).length > 0) {
    const roleName =
      typeof metadata.roleName === 'string' ? metadata.roleName : null;
    if (roleName) {
      lines.push(`**Role:** ${roleName}`);
    }
  }

  lines.push('', '---', '');
  return lines.join('\n');
}

function renderTierSection(
  tier: 1 | 2 | 3,
  candidates: ScoredCandidate[],
): string {
  const label = tierLabel(tier);
  const lines: string[] = [];
  lines.push(
    `## ${label} (${candidates.length} candidate${candidates.length !== 1 ? 's' : ''})`,
  );
  lines.push('');

  candidates.forEach((candidate, index) => {
    lines.push(renderCandidateCard(candidate, index + 1));
  });

  return lines.join('\n');
}

function renderCandidateCard(
  candidate: ScoredCandidate,
  rank: number,
): string {
  const lines: string[] = [];
  const lowConfTag = candidate.identity.lowConfidenceMerge
    ? ' **[Low-Confidence Merge]**'
    : '';
  lines.push(
    `### ${rank}. ${candidate.name} — ${Math.round(candidate.score.total)}/100${lowConfTag}`,
  );
  lines.push('');
  lines.push(`> ${candidate.narrative}`);
  lines.push('');
  lines.push(renderScoreBreakdown(candidate));

  const redFlags = renderRedFlags(candidate);
  if (redFlags) {
    lines.push(redFlags);
  }

  lines.push(renderEvidenceLinks(candidate));
  lines.push('---', '');
  return lines.join('\n');
}

function renderScoreBreakdown(candidate: ScoredCandidate): string {
  const lines: string[] = [];
  lines.push(
    '| Dimension | Score | Weight | Weighted | Confidence |',
  );
  lines.push(
    '|-----------|------:|-------:|---------:|-----------:|',
  );

  for (const comp of candidate.score.breakdown) {
    const dim = formatDimension(comp.dimension);
    lines.push(
      `| ${dim} | ${comp.raw} | ${comp.weight.toFixed(2)} | ${comp.weighted.toFixed(1)} | ${comp.confidence.toFixed(2)} |`,
    );
  }

  lines.push('');
  return lines.join('\n');
}

function renderRedFlags(candidate: ScoredCandidate): string | null {
  const flags = candidate.score.redFlags;
  if (flags.length === 0) return null;

  const lines: string[] = [];
  lines.push('**Red Flags:**');
  for (const flag of flags) {
    lines.push(`- ${severityIcon(flag.severity)} ${flag.signal} (${flag.severity}) — ${flag.evidenceId}`);
  }
  lines.push('');
  return lines.join('\n');
}

function renderEvidenceLinks(candidate: ScoredCandidate): string {
  if (candidate.evidence.length === 0) return '';

  const lines: string[] = [];
  lines.push('**Evidence:**');
  for (const ev of candidate.evidence) {
    lines.push(formatEvidenceItem(ev));
  }
  lines.push('');
  return lines.join('\n');
}

function formatEvidenceItem(ev: EvidenceItem): string {
  const urlPart = ev.url ? ` [link](${ev.url})` : '';
  return `- \\[${ev.id}\\] ${ev.claim} (${ev.adapter}, ${ev.confidence})${urlPart}`;
}

function renderFooter(): string {
  return `\n*Generated by Sourcerer on ${new Date().toISOString()}*\n`;
}

function tierLabel(tier: 1 | 2 | 3): string {
  switch (tier) {
    case 1:
      return 'Tier 1 — Strong Match';
    case 2:
      return 'Tier 2 — Moderate Match';
    case 3:
      return 'Tier 3 — Weak Match';
  }
}

function formatDimension(dimension: string): string {
  return dimension
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (c) => c.toUpperCase())
    .trim();
}

function severityIcon(severity: RedFlag['severity']): string {
  switch (severity) {
    case 'low':
      return '[low]';
    case 'medium':
      return '[med]';
    case 'high':
      return '[HIGH]';
  }
}
